spring:
  profiles:
    active: local
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:4321/city-information}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}

com:
  cityinformation:
    signingSecret: "S80G0VzprVmSfJbikczFInygBRVKhRHR"

integrations:
  weatherApi:
    apiKey: "15db842c6b2247f2aab173321230312"
